const CONSTANTES = {
  REGISTRO: 'REGISTRO',
  LOGIN: 'LOGIN',
  ESTABLECER_SESION: 'ESTABLECER_SESION',
  CERRAR_SESION: 'CERRAR_SESION',
  LIMPIAR_IMAGEN_SIGNUP: 'LIMPIAR_IMAGEN_SIGNUP',
  CARGAR_IMAGEN_SIGNUP: 'CARGAR_IMAGEN_SIGNUP',
  CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/ddbvsytpr/image/upload',
  CLOUDINARY_PRESET: 'vuntacks',
  CARGAR_IMAGEN_ADD: 'CARGAR_IMAGEN_ADD',
  LIMPIAR_IMAGEN_ADD: 'LIMPIAR_IMAGEN_ADD',

};

export default CONSTANTES;
